name: GCP CI/CD
on:
  pull_request:
    types:
      - closed

jobs:
  name: Backend Merge
  if_merged:
    if: github.event.pull_request.merged == true && github.head_ref == 'Backend'
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }} 
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }} 
        #passphrase: ${{ secrets.PASSPHRASE }} 
        port: 22
        script: |
          cd ${{ secrets.PWD }}
          git pull origin main
          cd ${{ secrets.PWD }}/BackendJS/BackendTS
          npm install
          pm2 restart Traffic