name: GCP CI/CD
on:
  push:
      branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }} 
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }} 
        passphrase: ${{ secrets.PASSPHRASE }} 
        port: 22
        script: |
            cd ${{ secrets.PWD }}
            git pull https://${{ secrets.GIT_TOKEN }}:x-oauth-basic@github.com/Mooboong/backend.git Develop
            npm install
            pm2 restart 1
