name: GCP CI/CD
on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }} 
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }} 
        #passphrase: ${{ secrets.PASSPHRASE }} 
        port: 22

    # npm 의존성 설치
    - name: npm install
      run: |
        cd ${{ secrets.PWD }}
        git pull origin main

    # Frontend Merge 시 React 빌드
    - name: React build
      if: github.head_ref == 'Frontend'
      run: |
        cd ${{ secrets.PWD }}/Backend/Frontend/creative
        pm2 stop Traffic
        npm install
        npm run build

    # Merge 하는 경우 서버 재시작
    - name: server restart
      run: |
        cd ${{ secrets.PWD }}/BackendJS/BackendTS
        npm install
        pm2 restart Traffic