name: GCP CI/CD 
yon:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true && github.head_ref == 'Backend'
    runs-on: ubuntu-latest
    steps:
    - name: Backend PR Merge
      run: |
        PR_BRANCH="${{ github.head_ref }}"
        echo $PR_BRANCH
    elif: github.event.pull_request.merged == true && github.head_ref == 'Frontend'
    runs-on: ubuntu-latest
    steps:
    - name: Frontend PR Merge
      run: |
        PR_BRANCH="${{ github.head_ref }}"
        echo $PR_BRANCH